seo: 
  site_name: 
  title: 
  description: 
  keywords: 
  social_image: 
  author: 
  favicon_image: 
social: 
  instagram_username:
  facebook_url:
  twitter_username: 
design: 
  dark-text_color: '#192837'
  medium-text_color: 'rgb(120 120 125)'
  light-text_color: '#E3ECE2'
  featured-text_color: '#ffbe00'
  dark_color: '#192837'
  medium_color: 'rgb(120 120 125)'
  light_color: '#ffffff'
  featured_color: '#ffbe00'
  accent_color: 'rgb(120 120 125)'