seo:
  site_name:
  title:
  description:
  keywords:
  social_image:
  author:
  favicon_image:
social:
  instagram_username:
  facebook_url:
  twitter_username:
design:
  dark-text_color: '#192837'
  medium-text_color: '#78787d'
  light-text_color: '#e3ece2'
  featured-text_color: '#ffbe00'
  dark_color: '#192837'
  medium_color: '#78787d'
  light_color: '#ffffff'
  featured_color: '#ffbe00'
  accent_color: '#78787d'
